// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEm2ygYieK_Rrc1WYlb98-zHSkVuwiCik',
    appId: '1:383308143268:android:0954d02b4bdab20bfd2431',
    messagingSenderId: '383308143268',
    projectId: 'heyroomie-d0f58',
    storageBucket: 'heyroomie-d0f58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuYDEtH-or_GyMudTX6msQD7KvFvwuWmI',
    appId: '1:383308143268:ios:032a7d8d4be845bdfd2431',
    messagingSenderId: '383308143268',
    projectId: 'heyroomie-d0f58',
    storageBucket: 'heyroomie-d0f58.appspot.com',
    androidClientId: '383308143268-0562onhf8k458ktman935hb1vqo1ivk8.apps.googleusercontent.com',
    iosClientId: '383308143268-u5nu30rvdelj4s0a8tnha56fvt1snab6.apps.googleusercontent.com',
    iosBundleId: 'com.rego.heyroomi',
  );
}
